// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Remedios.Api.Data;

#nullable disable

namespace Remedios.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.5");

            modelBuilder.Entity("Remedios.Api.Models.ControleAbertura", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UltimaAbertura")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ControleAbertura");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            UltimaAbertura = new DateTime(2026, 5, 23, 3, 5, 50, 257, DateTimeKind.Utc).AddTicks(7559)
                        });
                });

            modelBuilder.Entity("Remedios.Api.Models.Receita", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("DataEmissao")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("DataUltimoUso")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("DataValidade")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<bool>("Devolvida")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LocalGuardada")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<string>("NomeUltimoUsuario")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("QuantidadeUsos")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Receitas");
                });

            modelBuilder.Entity("Remedios.Api.Models.Remedio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("TEXT");

                    b.Property<string>("Bula")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ComprimidosPorDia")
                        .HasPrecision(10, 2)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("QuantidadeAtual")
                        .HasPrecision(10, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("QuantidadeMinima")
                        .HasPrecision(10, 2)
                        .HasColumnType("TEXT");

                    b.Property<int?>("ReceitaId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ReceitaId");

                    b.ToTable("Remedios");
                });

            modelBuilder.Entity("Remedios.Api.Models.Remedio", b =>
                {
                    b.HasOne("Remedios.Api.Models.Receita", "Receita")
                        .WithMany("Remedios")
                        .HasForeignKey("ReceitaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Receita");
                });

            modelBuilder.Entity("Remedios.Api.Models.Receita", b =>
                {
                    b.Navigation("Remedios");
                });
#pragma warning restore 612, 618
        }
    }
}
